### PR TITLE
Use ASL 3.1.0

### LINKED ISSUE #16: Breaks with GCC 6
See ampl/mp#85.

Would require changing to ~~https://github.com/gidden/mp, which has the fix, but not the release 2.1.1, or to~~ 3.1.0.

### PR DESCRIPTION
**Pull request by abelsiqueira**
Closes #16

### CODE REVIEW

**Comment by dpo** [comment]
Excellent, thank you. I'm updating the Homebrew formulas as we speak.

**Comment by abelsiqueira** [comment]
But wait, the OSX builds are failing because of CMake. And the linux might too. It needs 3.3 now.

**Comment by abelsiqueira** [comment]
I'm testing the cmake currently. For linux was easy, so I'm checking for osx.

**Comment by abelsiqueira** [comment]
This will pass now.

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
